### ISSUE TITLE
npm run scripts should be documented in README.md

### ISSUE THREAD

**Issue by mkuzak** [nlesc-sherlock/punchcardjs#30]
Currently there is no documentation of the tasks available to run with `npm run`. There is no good way to document it in package.json so my suggestion is to document it in `README.md`.

**Comment by jspaaks** [comment]
add dependency graph maybe

**Comment by jspaaks** [comment]
I've added a callgraph of the tasks to the readme, but the tasks themselves are currently not documented

**Comment by jspaaks** [comment]
from the callgraph, the only tasks that are currently not mentioned are
- `preversion`, `version`, `postversion`, npm default task plus not intended for other users
- `everything`, which is just a convenience task for running `tsdoc` and `cover`
  So it looks like we've covered everything; closing this issue.
